name: Nilgiri_Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Run every night at midnight UTC
  workflow_dispatch:
    inputs:
      custom_feature_file:
        description: 'Custom feature file to run test'
        required: true
        default: ''

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install

      - name: Run Tests
        run:
        |
          echo "Received event: ${{ github.event.inputs.custom_feature_file }}"
          echo "Custom feature file: ${{ github.event.inputs.custom_feature_file }}"
          if [ -n "${{ github.event.inputs.custom_feature_file }}" ]; then
            echo "Running custom feature file: ${{ github.event.inputs.custom_feature_file }}"
            npm run cucumberRun "${{ github.event.inputs.custom_feature_file }} || true"
          else
            # Run the full suite
            npm run automation -- --headed=false
          fi

      - name: Generate Report
        run: npm run posttest
        