name: Nilgiri_Automation

on:
  workflow_run:
    workflows: ["Nilgiri Automation"]
    types:
      - completed

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install

      - name: Run Tests
        run: |
          if [ -n "${{ github.event.inputs.custom_feature_file }}" ]; then
            echo "Running custom feature file: ${{ github.event.inputs.custom_feature_file }}"
            npm run cucumberRun "${{ github.event.inputs.custom_feature_file }}"
          else
            # Run the full suite
            npm run automation -- --headed=false
          fi

      - name: Generate Report
        run: npm run posttest
