name: Nilgiri_Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Run every night at midnight UTC
  workflow_dispatch:
    inputs:
      custom_feature_file:
        description: 'Custom feature file to run'
        required: false
        default: ''

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run nilgiriDependencyInstall

      - name: Install Playwright
        run: npx playwright install

      - name: Run Tests
        run: |
          if [ -n "${{ inputs.client_payload.custom_feature_file }}" ]; then
            echo "Running custom feature file: ${{ inputs.client_payload.custom_feature_file }}"
            npm run cucumberRun "${{ inputs.client_payload.custom_feature_file }}"
          else
            # Run the full suite
            npm run automation -- --headed=false
          fi

      - name: Generate Report
        run: npm run posttest